env:
  browser: true
  es6: true
extends:
  - 'plugin:react/recommended'
  - standard
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 2018
  sourceType: module
plugins:
  - react
  - prettier
  - eslint-plugin-import-helpers
rules:
  indent: ['error', 2, { 'SwitchCase': 1 }]
  semi: ['error', 'never']
  quotes: ['error', 'single']
  jsx-quotes: ['error', 'prefer-single']
  no-underscore-dangle: ['off']
  react/jsx-filename-extension: ['error', { 'extensions': ['.js', '.jsx'] }]
  react/prop-types: ['warn']
  space-before-function-paren: ['off']
  import-helpers/order-imports:
    [
      'warn',
      {
        'newlinesBetween': 'always',
        groups:
          [
            '/^react/',
            'module',
            '/^@material-ui/core/',
            '/^@material-ui/lab/',
            '/^@material-ui/icons/',
            '/^src/icons/',
            '/^src/components/',
            '/^src/routes/',
            '/^src/containers/',
            '/^src/views/',
            '/^src/routers/',
            '/^src/graphql/',
            '/^src/contexts/',
            '/^src/forms/',
            '/^src/hooks/',
            '/^src/dialogs/',
            '/^src/validators/',
            '/^src/utils/',
            '/^src/services/',
            '/^src/firebase/',
            ['parent', 'sibling', 'index'],
          ],
        alphabetize: { order: 'asc', ignoreCase: true },
      },
    ]
